### ISSUE TITLE
when I read hdr I got a error [error during reading file ]

### ISSUE THREAD

**Issue by hepra** [kopaka1822/ImageViewer#23]
![image](https://user-images.githubusercontent.com/15621729/168036506-b1ee2f51-d94b-455d-854f-2900cd03b47a.png)

**Comment by kopaka1822** [comment]
hello, can you send me the .hdr file?

**Comment by hepra** [comment]
it's too large. Could you please provide your email address?

**Comment by kopaka1822** [comment]
felixbruell@live.de

**Comment by kopaka1822** [comment]
I will try to look at this issue tomorrow. Today I won't have enough time to resolve this

**Comment by hepra** [comment]
I use this project solve my problem, https://github.com/bluescan/tacentview , thanks anyway~

**Comment by kopaka1822** [comment]
I have discovered that my current hdr image loader does not support larger images, which is why it didn't work for your image.
I will try to replace the hdr loader with a different loader, that supports larger images, in the future.
I also discovered that you can open your hdr image in Gimp (https://www.gimp.org/)

**Comment by hepra** [comment]
Thanks~ and Best Regards


dahe
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kopaka1822/ImageViewer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月13日(星期五) 下午4:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kopaka1822/ImageViewer] when I read hdr I got a error [error during reading file ] (Issue #23)





 
I have discovered that my current hdr image loader does not support larger images, which is why it didn't work for your image.
 I will try to replace the hdr loader with a different loader, that supports larger images, in the future.
 I also discovered that you can open your hdr image in Gimp (https://www.gimp.org/)

**Comment by kopaka1822** [comment]
I replaced the previous hdr loader with a different loader that can load larger files.
However, it appears that DirectX does not support images that are larger than 16384 pixels, it still does not work (since your texture is ~19000 pixels in width).
I do not plan to make a workaround for this, since the viewer uses DirectX textures internally to process everything quickly.

Still, thanks for pointing out the issue with the hdr file and I'm sorry that I cannot help in this case.
