### ISSUE TITLE
8K Cubemap

### ISSUE THREAD

**Issue by Carandiru0** [kopaka1822/ImageViewer#29]
Entering 8192 into field for latlong to cubemap and hitting ok causes program to exit. With the same texture, 4096 works and does not crash.

It would be great if I could produce a 8K cubemap from a 8K equirectangular image.

Great program btw, very useful and certaintly has great usable features! KTX & KTX2 support are top-notch!

Windows 10
NVIDIA Geforce 3060, latest drivers.

Thanks!

**Comment by kopaka1822** [comment]
Hello,
is your source equirectangular image an HDR file (.hdr or another float format) or LDR (png, jpg, bmp)?

**Comment by Carandiru0** [comment]
it's a png, 16bpc greyscale.

**Comment by kopaka1822** [comment]
Hi, 
I investigated the source of the problem.
The problem is that the Image Viewer mainly works with RGBA32 float formats internally (this is easier to handle for me since this format supports all relevant features in DirectX).
The problem is now, that your (and my) hardware cannot create an image with 8k size since it requires too much memory with the RGBA32 float format: 8192x8192x16 (bytes per pixel) x 6 (faces) = 6442450944 = 6GB (Technically, my graphics card has enough memory for this, but it doesn't want to allocate an image this big).
For now, this operation will at least display an error message instead of crashing the application after the latest commit.

However, I do not have plans for now to support 16 bpc formats as internal image viewer formats, since this would require a lot of code changes... I will keep it in mind though

I am sorry that 4k appears to be the biggest resolution for now

**Comment by Carandiru0** [comment]
6GB? I don't know why I didn't think of this - thanks for looking into the problem - I feel rather dumb now considering that having a single resource on the gpu of that size is so wasteful. Even with BC7/BC6 compression it would probably be too large. 
Sorry I forgot about the x6 faces of a cubemap when it comes to memory requirements.
 I'm really glad to here that internally 32bpc is used on the images, this allows for all the 16bpc usage I require!
Great application by the way, I love how I can pack multichannel images in a custom way with the command strings eg.) "rgb(red(I0), red(I1), green(I1))"
Cheers!
