### ISSUE TITLE
The type initializer for 'ImageFramework.DirectX.Device' threw an exception

### ISSUE THREAD

**Issue by AnonN10** [kopaka1822/ImageViewer#32]
Crashes with: "The type initializer for 'ImageFramework.DirectX.Device' threw an exception.", and no additional information
Specs: Windows 7 x64 D3D11 compatible GPU (GeForce 710M)

**Comment by kopaka1822** [comment]
Hello, this is the function that tries to create the directX device. I dont know why it crashes, I just read online that similar errors occur when x32 dlls are loaded instead of x64.
I am actually surprised that it even runs on windows 7, since it uses a windows 10 sdk (which works on windows 8 at least).
Unfortunately I cannot debug this since I have neither the graphics card nor windows 7.
If you are experienced with visual studio you can try to debug this. Some instructions are given here: https://github.com/kopaka1822/ImageViewer/blob/master/Docs/build.md

**Comment by Hatschi-lab** [comment]
Hello Kopaka1822,
I have the same issue on a win8.1 installation and an intel hd 4600 GPU with the ImageViewer version 3.8 .
The ThumbnailHandler.dll also doesn't work after registering, it just shows the loading bar for a long time but no thumbnails are generated.
The ImageViewer as well as the thumbnail generatation works fine when using version 3.7.
I also can confirm that ImageViewer 3.8 works fine when on win10 or win11.
It would be great if you could have another look at this issue.

Update: 
The drawback of using the 3.7 version for thumbnails is, that it doesn't create thumbnails
for KTX images that do have an alpha channel. But that can be fixed by just copying over the DxImageLoader.dll from the 3.8 version in the folder from the 3.7 version to replace the original one. ImageViewer still works as well.
